'use client';

/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/bjRyoIzlUob
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Archivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

archivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
* */

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.5rem;
}
* */
import React from 'react';
import { Card, CardTitle } from '@/components/ui/card';
import { TabsTrigger, TabsList, TabsContent, Tabs } from '@/components/ui/tabs';
import {
  TableHead,
  TableRow,
  TableHeader,
  TableCell,
  TableBody,
  Table,
} from '@/components/ui/table';
import { Button } from '@/components/ui/button';

export const Issueform = () => (
  <div className="grid grid-cols-1 md:grid-cols-[1fr_300px] gap-6 p-6 w-full">
    <div className="grid gap-6">
      <Card className="p-6">
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <h2 className="text-2xl font-bold">Tag summary</h2>
            <div className="flex items-center gap-2">
              <CalendarDaysIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span className="text-sm text-gray-500 dark:text-gray-400">
                May 2023
              </span>
            </div>
          </div>
          <div className="grid sm:grid-cols-2 lg:grid-cols-3 gap-4">
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Tax Free Tag ID
              </div>
              <div className="text-3xl font-bold">T252024000</div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Status
              </div>
              <div className="text-3xl font-bold">Issued</div>
            </div>
            <div className="bg-gray-100 dark:bg-gray-800 rounded-lg p-4 flex flex-col gap-2">
              <div className="text-sm text-gray-500 dark:text-gray-400">
                Issued Date
              </div>
              <div className="text-xl font-bold">3.06.2024 15:26</div>
              {/* grey small text */}
              <div className="text-xl font-bold">3.09.2024 15:26</div>
            </div>
          </div>
          <div className="grid sm:grid-cols-3 gap-4">
            <Card className="p-4">
              <CardTitle>Export Validation</CardTitle>
              <div className="grid gap-2 pt-2">
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Export date: May 15, 2023
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Export location: New York, NY
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Stamp type: Standard
                </div>
              </div>
            </Card>
            <Card className="p-4">
              <CardTitle>Refund</CardTitle>
              <div className="grid gap-2 pt-2">
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Submission date: April 20, 2023
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Paid date: April 25, 2023
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Refund location: Los Angeles, CA
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Status: Approved
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Refund method: Credit Card
                </div>
              </div>
            </Card>
            <Card className="p-4">
              <CardTitle>Invoicing</CardTitle>
              <div className="grid gap-2 pt-2">
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Invoice date: June 1, 2023
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Invoice number: 12345
                </div>
                <div className="text-sm text-gray-500 dark:text-gray-400">
                  Invoice status: Paid
                </div>
              </div>
            </Card>
          </div>
        </div>
      </Card>
      <div className="border shadow-sm rounded-lg overflow-hidden">
        <Tabs defaultValue="merchants">
          <TabsList className="bg-gray-100 dark:bg-gray-800 grid grid-cols-3">
            <TabsTrigger value="merchants">Purchase Details</TabsTrigger>
            <TabsTrigger value="travelers">Tag History</TabsTrigger>
            <TabsTrigger value="trips">Export Validation</TabsTrigger>
          </TabsList>
          <TabsContent value="merchants">
            {/* two clolumn div */}

            <div className="grid grid-cols-1 md:grid-cols-[1fr_300px] gap-6 p-6 ">
              <div className="grid gap-6">
                <Card className="p-4 max-w-96">
                  <CardTitle>TOTALS</CardTitle>
                  <div className="grid gap-2 pt-2">
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        SALES AMOUNT
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        2.999,90 ₺
                      </div>
                    </div>
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        VAT
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        amount
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>{' '}
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        gross
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>{' '}
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        refund
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>
                  </div>
                </Card>
              </div>
              <div className="grid gap-6">
                <Card className="p-4 max-w-96">
                  <CardTitle>EARNINGS</CardTitle>
                  <div className="grid gap-2 pt-2">
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Gross Commission
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        2.999,90 ₺
                      </div>
                    </div>
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        redeeming
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Rebate
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>{' '}
                    <div className="flex justify-between">
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        Net Comission
                      </div>
                      <div className="text-sm text-gray-500 dark:text-gray-400">
                        272,72 ₺
                      </div>
                    </div>{' '}
                  </div>
                </Card>
              </div>
            </div>
          </TabsContent>
          <TabsContent value="travelers">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Email</TableHead>
                  <TableHead>Location</TableHead>
                  <TableHead className="text-right">Total Trips</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">Emily Davis</TableCell>
                  <TableCell>emily@example.com</TableCell>
                  <TableCell>San Francisco, CA</TableCell>
                  <TableCell className="text-right">12</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Michael Brown</TableCell>
                  <TableCell>michael@example.com</TableCell>
                  <TableCell>Boston, MA</TableCell>
                  <TableCell className="text-right">8</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Olivia Wilson</TableCell>
                  <TableCell>olivia@example.com</TableCell>
                  <TableCell>Seattle, WA</TableCell>
                  <TableCell className="text-right">15</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">
                    William Anderson
                  </TableCell>
                  <TableCell>william@example.com</TableCell>
                  <TableCell>Chicago, IL</TableCell>
                  <TableCell className="text-right">9</TableCell>
                </TableRow>
                <TableRow>
                  <TableCell className="font-medium">Sophia Martinez</TableCell>
                  <TableCell>sophia@example.com</TableCell>
                  <TableCell>Miami, FL</TableCell>
                  <TableCell className="text-right">11</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TabsContent>
          <TabsContent value="trips">
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Created on</TableHead>
                  <TableHead>Scan by</TableHead>
                  <TableHead>Matchd</TableHead>
                  <TableHead>Hit</TableHead>
                  <TableHead>Revalidated</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                <TableRow>
                  <TableCell className="font-medium">12.1.1990</TableCell>
                  <TableCell>Tom Wilson</TableCell>
                  <TableCell>✅</TableCell>
                  <TableCell>✅</TableCell>
                  <TableCell>✅</TableCell>
                </TableRow>
              </TableBody>
            </Table>
          </TabsContent>
        </Tabs>
      </div>
    </div>
    <div className="grid gap-6">
      <Card className="p-6">
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xl font-bold">Merchant Details</h3>
            <Button size="sm" variant="outline">
              View Merchant
            </Button>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center gap-2">
              <UserIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span className="font-medium">Unirefund</span>
            </div>
            <div className="flex items-center gap-2">
              <MailIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>product groups: marine parts, etc</span>
            </div>
            <div className="flex items-center gap-2">
              <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>Address: New York, NY, USA</span>
            </div>
            <div className="flex items-center gap-2">
              <DollarSignIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>$25,000 total sales</span>
            </div>
          </div>
        </div>
      </Card>
      <Card className="p-6">
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xl font-bold">Traveler Details</h3>
            <Button size="sm" variant="outline">
              View Traveler
            </Button>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center gap-2">
              <UserIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span className="font-medium">Emily Davis</span>
            </div>
            <div className="flex items-center gap-2">
              <MailIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>emily@example.com</span>
            </div>
            <div className="flex items-center gap-2">
              <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>Residency: Turkey</span>
            </div>
            <div className="flex items-center gap-2">
              <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>Citizeship: Turkey</span>
            </div>
          </div>
        </div>
      </Card>
      <Card className="p-6">
        <div className="grid gap-4">
          <div className="flex items-center justify-between">
            <h3 className="text-xl font-bold">Trip Details</h3>
            <Button size="sm" variant="outline">
              View Trip
            </Button>
          </div>
          <div className="grid gap-2">
            <div className="flex items-center gap-2">
              <CalendarDaysIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span className="font-medium">Visit</span>
            </div>
            <div className="flex items-center gap-2">
              <MapPinIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>Flight number</span>
            </div>
            <div className="flex items-center gap-2">
              <PlaneIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>Departure: Turkey</span>
            </div>
            <div className="flex items-center gap-2">
              <PlaneIcon className="w-5 h-5 text-gray-500 dark:text-gray-400" />
              <span>Destination: Saudi Arabia</span>
            </div>
          </div>
        </div>
      </Card>
    </div>
  </div>
);

const CalendarDaysIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M8 2v4" />
    <path d="M16 2v4" />
    <rect width="18" height="18" x="3" y="4" rx="2" />
    <path d="M3 10h18" />
    <path d="M8 14h.01" />
    <path d="M12 14h.01" />
    <path d="M16 14h.01" />
    <path d="M8 18h.01" />
    <path d="M12 18h.01" />
    <path d="M16 18h.01" />
  </svg>
);

const DollarSignIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <line x1="12" x2="12" y1="2" y2="22" />
    <path d="M17 5H9.5a3.5 3.5 0 0 0 0 7h5a3.5 3.5 0 0 1 0 7H6" />
  </svg>
);

const MailIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <rect width="20" height="16" x="2" y="4" rx="2" />
    <path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7" />
  </svg>
);

const MapPinIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z" />
    <circle cx="12" cy="10" r="3" />
  </svg>
);

const PlaneIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M17.8 19.2 16 11l3.5-3.5C21 6 21.5 4 21 3c-1-.5-3 0-4.5 1.5L13 8 4.8 6.2c-.5-.1-.9.1-1.1.5l-.3.5c-.2.5-.1 1 .3 1.3L9 12l-2 3H4l-1 1 3 2 2 3 1-1v-3l3-2 3.5 5.3c.3.4.8.5 1.3.3l.5-.2c.4-.3.6-.7.5-1.2z" />
  </svg>
);

const UserIcon = (props) => (
  <svg
    {...props}
    xmlns="http://www.w3.org/2000/svg"
    width="24"
    height="24"
    viewBox="0 0 24 24"
    fill="none"
    stroke="currentColor"
    strokeWidth="2"
    strokeLinecap="round"
    strokeLinejoin="round"
  >
    <path d="M19 21v-2a4 4 0 0 0-4-4H9a4 4 0 0 0-4 4v2" />
    <circle cx="12" cy="7" r="4" />
  </svg>
);
